MutationType:
    type: object
    config:
        fields:
            importUsers:
                type: "ImportUsersPayload!"
                resolve: "@=service('App\\\\Infrastructure\\\\GraphQL\\\\Mutation\\\\User\\\\ImportUsersMutation').__invoke()"

            promoteUserToAdmin:
                type: "UserType!"
                args:
                    userId:
                        type: "String!"
                resolve: "@=service('App\\\\Infrastructure\\\\GraphQL\\\\Mutation\\\\User\\\\PromoteUserToAdminMutation').__invoke(args)"

            createTask:
                type: "TaskType"
                args:
                    title:
                        type: "String!"
                    description:
                        type: "String!"
                    assignedUserId:
                        type: "String!"
                resolve: "@=service('App\\\\Infrastructure\\\\GraphQL\\\\Resolver\\\\TaskResolver').resolveCreate(args)"

            updateTaskStatus:
                type: "TaskType"
                args:
                    taskId:
                        type: "String!"
                    status:
                        type: "String!"
                resolve: "@=service('App\\\\Infrastructure\\\\GraphQL\\\\Resolver\\\\TaskResolver').resolveUpdateStatus(args)"